#!/bin/bash
#Explicitly adds files in .secrets to git commit
BRANCH=$(git rev-parse --abbrev-ref HEAD)
WORKING_ROOT=$(git rev-parse --show-toplevel)
SECRETS_PATH="$WORKING_ROOT/.secrets"
SECRETS_EXT=".secret"
#SECRETS_RECEIPIENT=$"'Andre Mottier'"
SECRETS_HOMEDIR="/home/www-data/.gnupg"

echo "Starting commit for branch: $BRANCH"
echo "Hiding secrets"
if [ -f $SECRETS_PATH ]; then
    while read -r line; do
        if [ ${line:0:1} != "#" ]; then
            old_fn="$WORKING_ROOT/$line"
            new_fn="$WORKING_ROOT/$line$SECRETS_EXT"
            if [ -f $old_fn ]; then
                sudo gpg --homedir $SECRETS_HOMEDIR --yes --trust-model always -r "Andre Mottier" -o $new_fn -eq $old_fn
                
                if [ -f $new_fn ]; then
                    git add $new_fn
                else
                    echo "Failed to encrypt $old_fn"
                fi
            else
                echo "File $old_fn not found. Skipping."
            fi
        fi
    done < $SECRETS_PATH
else
    echo ".secrets file not found at: $SECRETS_PATH"
fi